### ISSUE TITLE
Filter <form> tag

### ISSUE THREAD

**Issue by wonderlandpark** [micromark/micromark-extension-gfm#2]
### Subject of the feature

Escape `<form>` tag

### Problem

It does not escape `<form>` tag so it is able to send POST requests by using something like `<button type='submit'>Button</button>` inside the form tag

### Expected behavior

Form tag should not work just like github

### Alternatives

It should ignore form tag

**Comment by wooorm** [comment]
micromark is secure by default. You’re probably setting `allowDangerousHtml` somewhere?
In which case, see https://github.com/micromark/micromark#security for more information
