### ISSUE TITLE
Autolinks get detected in raw HTML, leading to invalid markup

### ISSUE THREAD

**Issue by trieloff** [micromark/micromark-extension-gfm#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

 micromark-extension-gfm@15.14.0

### Link to runnable example

https://github.com/micromark/micromark-extension-gfm/pull/4

### Steps to reproduce

See https://github.com/micromark/micromark-extension-gfm-autolink-literal

### Expected behavior

Autolinks within existing HTML `a` tags should not create another link, but be left alone.

### Actual behavior

A link is created within the link.

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

**Comment by wooorm** [comment]
Same as GH-4!
